### ISSUE TITLE
[Proposal] Modern Web Development with Javalin and JavalinVue

### ISSUE THREAD

**Issue by ivanosevic** [JavaDominicano/monthly-talks#19]
### Título

Modern Web Development with Javalin and JavalinVue

### Fecha

Miércoles 21 de Junio, 2023

### Hora

7:30PM - 8:30PM

### Descripción

¿Quieres empezar a crear una aplicación fullstack con Java y VueJS? El framework web Javalin te brinda, JavalinVue, un plugin que da soporte para desarrollar frontends con Vue de una manera simplificada en tu mismo proyecto. Junto a Javalin, hacen una combinación interesante que nos ayudarán a empezar a trabajar en nuestro proyecto en cuestión de minutos. 

En esta charla, veremos los fundamentos de Javalin y JavalinVue para crear una aplicación fullstack, y la aplicación de los mismos en un proyecto pequeño. Al final, estaremos analizando tanto las ventajas y desventajas de utilizar las tecnologías previamente mencionadas. 

### Bio

Mi nombre es Ivanosevic García. Tengo alrededor de 3 años de experiencia en el mundo del desarrollo conjunto al aseguramiento de calidad de software. Actualmente soy desarollador de Java, y me apasiona ver los nuevos avances al nivel de lenguaje y nuevos proyectos basados en Java. Con relación a la tecnología de Javalin, estoy creando proyectos desde su versión 3.9, que fue lanzada en 2021, y desde entonces he seguido el proyecto. Aparte de haber creado varios proyectos en esta tecnología, me siento confiado en que puedo transmitir mis conocimientos de las versión actual, sobre la misma y de JavalinVue. 

Perfil de GitHub: https://github.com/Ivanosevic

**Comment by ecabrerar** [comment]
Hola @ivanosevic , me parece interesante tu propuesta, hay un punto a discutir, las reuniones la hacemos día miércoles, te parece bien, miércoles 21 de Junio en lugar de viernes 23?

**Comment by ivanosevic** [comment]
@ecabrerar No hay problema con moverla para el miércoles 21 de Junio.

**Comment by ecabrerar** [comment]
Hola @ivanosevic , haremos la publicación de tu charla para esta semana. Tenía agendado el 21 como lo conversamos?

**Comment by ivanosevic** [comment]
Saludos, @ecabrerar, como acordamos, el 21 de junio estaré disponible para dar la charla. Cualquier cosa de mi lado que se requiera, me dejas saber. 👍

**Comment by ecabrerar** [comment]
La tarea está siendo trabajada en el issue #20
