### ISSUE TITLE
[Proposal] Playing with Java and Playwright 

### ISSUE THREAD

**Issue by SiriusDarkz** [JavaDominicano/monthly-talks#27]
### Título

Playing with Java and Playwright 

### Fecha

24/10/2023

### Hora

7 PM

### Descripción

Muchas personas a la hora de trabajar Automation, o Sofware Testing Automation, han adoptado otras herramientas como Python o JS, pensando que en Java solo contamos con un lenguaje verboso y desfazado con un framework igual de aburrido como Selenium, esta charla viene a desmentir esto, mostrando lo divertido y simple que puede resultar esta tarea con Java usando Playwright.

### Bio

Software Engineer trabajando con Java.

**Comment by ecabrerar** [comment]
@SiriusDarkz vamos a realizar esta sesión el día 15 de noviembre del 2023 a la 7:00 P.M.
