### ISSUE TITLE
Programar conversatorio para el mes de febrero 2023

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/monthly-talks#3]
Al cerrar la encuesta que tenemos en la comunidad, se debe establecer la fecha y hora para la realización del conversatorio de febrero.

**Comment by ecabrerar** [comment]
Ver propuesta: https://www.canva.com/design/DAFZ7Lb2zUc/XJykpMab-87l63Op8OCuUg/edit?utm_content=DAFZ7Lb2zUc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by BrayanMnz** [comment]
Fecha tentativa : Martes 21 Febrero, 2023. 

Corregir typo en el título de https://www.canva.com/design/DAFZ7Lb2zUc/XJykpMab-87l63Op8OCuUg/edit?utm_content=DAFZ7Lb2zUc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton 

Mont**h**ly

**Comment by ecabrerar** [comment]
@BrayanMnz corregí el typo, favor darle un vistazo nuevamente

**Comment by ecabrerar** [comment]
Evento publicado :https://www.eventbrite.com/e/tendencias-en-el-ecosistema-java-para-el-2023-tickets-539748501297
![MonthlyTalks-EP 01](https://user-images.githubusercontent.com/2789130/217657231-023e3520-66e1-44c9-8e7f-cc9eb4f63e53.jpg)

**Comment by ecabrerar** [comment]
Listo!
