### ISSUE TITLE
Crear banner en canva referente a Java 21

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/monthly-talks#41]
Titulo: 
EXPLORANDO ALGUNAS FUNCIONALIDADES DE JDK 21
Incluir imágenes de los exponentes
![Explorando algunas funcionalidades de Java 21](https://github.com/JavaDominicano/monthly-talks/assets/2789130/e1a5b696-2eea-4e64-a9c8-e1b70fa99095)

Incluir el logo de Java Dominicano.
Incluir el logo de la escuela de ICC https://github.com/JavaDominicano/conference/blob/master/src/jbake/assets/img/supporters/pucmm-ect.png
Nota:
No incluir el logo de Java de Marca Registrada.

**Comment by ecabrerar** [comment]
@fredpena crees que puedes ayudarme con esto?

**Comment by fredpena** [comment]
Adjunto imagen.

![CONF-JAVA-21](https://github.com/JavaDominicano/monthly-talks/assets/5680906/67d0ebe3-f053-4784-8d7c-4e1735f8687b)
