### ISSUE TITLE
[WorkShop] Construyendo Aplicaciones Web Modernas y Escalables con Java

### ISSUE THREAD

**Issue by fredpena** [JavaDominicano/monthly-talks#43]
### Título
- `Construyendo Aplicaciones Web Modernas y Escalables con Java`

### Modalidad
- Preferiblemente presencial

### Tiempo
- 4 horas

### Fecha
- A determinar

### Descripción
¿Quieres aprender a construir aplicaciones web modernas y escalables? Únete a nuestro taller `Construyendo Aplicaciones Web Modernas y Escalables con Java`, donde explorarás las tecnologías clave, como Spring Boot, Vaadin Flow, Docker, Traefik, Terraform y Ansible, que están transformando el mundo del desarrollo de software. Aprenderás a crear aplicaciones web de alto rendimiento y a desplegarlas en contenedores, asegurando la escalabilida,  la eficiencia y la seguridad. Desde la creación del back-end con Spring Boot hasta la construcción de interfaces de usuario atractivas con Vaadin Flow, y la administración de la infraestructura con Terraform y Ansible, este taller te brindará las habilidades esenciales para llevar tus proyectos al siguiente nivel. Únete a nosotros y prepárate para llevar tus habilidades de desarrollo al futuro. ¡No te pierdas esta oportunidad de aprender y crecer en el mundo de la tecnología!

**Comment by ecabrerar** [comment]
@fredpena vamos a realizar el taller el 25 de noviembre del presente año.
