### ISSUE TITLE
[Monthly Talks 2023 - EP.07] Crear banner para la reunión de noviembre 2023

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/monthly-talks#48]
Crear banner para la presentación relacionada al issue #47

**Comment by ecabrerar** [comment]
@fredpena favor ayudarnos con esta tarea, ya existe una plantilla para estos temas, sería utilizar la plantilla.

**Comment by fredpena** [comment]
> @fredpena favor ayudarnos con esta tarea, ya existe una plantilla para estos temas, sería utilizar la plantilla.

Favor de compartirme la plantilla.

**Comment by ecabrerar** [comment]
Te compartí la plantilla

**Comment by fredpena** [comment]
Listo!!!

**Comment by ecabrerar** [comment]
![MonthlyTalks-EP07](https://github.com/JavaDominicano/monthly-talks/assets/2789130/5e48a7cb-4b3d-4ea1-b3a5-3daf2cea1bd8)

**Comment by ecabrerar** [comment]
Fue sustituido por este banner .
![MonthlyTalks-EP07](https://github.com/JavaDominicano/monthly-talks/assets/2789130/3fd9ba21-f02b-4b98-a4f9-77c3ebe130fa)
