### ISSUE TITLE
[Monthly Talks 2023 - EP.02] - Cómo crear tu primera API REST con Spring Boot 

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/monthly-talks#5]
**Titulo:** Cómo crear tu primera API REST con Spring Boot
**Fecha:** 29 de Marzo de 2023
  Hora: 7:00 P.M. - 8:30 P.M.
  Invitado: Rafael Saldaña R
 Descripción:
Con Spring Boot nos facilitamos las configuraciones como las dependencias de conexión con la base de datos, despliegue del servidor, entre otras.

En esta presentación vamos a mostrar como crear tu primer  API REST y será documentado con Swagger 3.

Herramientas a utilizar:

Spring Web
Spring Boot DevTools
Spring Data JPA
Postgres
Maven
Swagger

Bio:

**Comment by rsaldanar** [comment]
Rafael Saldaña
Ingeniero en Sistemas y Computación
Desarrollador de Software con experiencia en desarrollo backend
Actualmente trabajo en Claro
Java, Spring Boot, Postgres, Oracle, SQL Server, My SQL, Linux, OS X
Padre y Esposo full-Time, Entusiasta de la tecnología, aficionado del Aikido y las Películas
linkedin: https://www.linkedin.com/in/rafael-saldaña-richardson-8b4146b8/
gibhub: https://github.com/rsaldanar

**Comment by ecabrerar** [comment]
gracias por la información @rsaldanar
