### ISSUE TITLE
Crear banner para la presentación del EP.02

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/monthly-talks#6]
Crear banner para la presentación relacionada al issue #5

**Comment by ecabrerar** [comment]
![EP 02-API-REST-SB](https://user-images.githubusercontent.com/2789130/226795784-46fa2410-f881-46da-ad2e-3254bd6f7877.jpg)

**Comment by ecabrerar** [comment]
@BrayanMnz  favor darle un vistazo

**Comment by BrayanMnz** [comment]
> @BrayanMnz favor darle un vistazo

Me parece bien! 
podemos publicarlo de mi parte

**Comment by zerh** [comment]
LGTM, 👍
