### ISSUE TITLE
[Proposal] Java Annotation Processing

### ISSUE THREAD

**Issue by jmorla** [JavaDominicano/monthly-talks#61]
### Título

Java Annotation Processing

### Fecha

April 9, 2024

### Hora

7:00 PM EST

### Descripción

JSR 269 es una poderosa herramienta para mejorar y personalizar el código de una aplicación mediante el uso de anotaciones. Puede ser utilizado para automatizar tareas durante la compilación y sirve como la base para el funcionamiento de librerias como Lombok, MapStruct, JSTachio y Apache Velocity.

### Bio

Hola! soy Jorge Morla un ingeniero de graduado de la O&M Dominicana con más de 8 años de experiencia en Java. Mi pasión por la programación se refleja en mi entusiasmo por enfrentar retos que pongan a prueba mis habilidades y me impulsen a buscar soluciones innovadoras.

Con una sólida formación en desarrollo de software, he trabajado en diversos proyectos que abarcan desde aplicaciones empresariales hasta soluciones específicas de la industria. Mi experiencia me ha permitido no solo perfeccionar mis habilidades técnicas en Java, sino también desarrollar un enfoque práctico para abordar los desafíos del desarrollo de software.

Me apasiona explorar nuevas tecnologías y adoptar enfoques innovadores en el diseño y la implementación de software. La resolución de problemas y la creación de soluciones prácticas son el núcleo de mi enfoque, y siempre estoy ansioso por aprender y aplicar nuevas ideas en mis proyectos.

**Comment by ecabrerar** [comment]
Propuesta aceptada, se trabajará en el issue #70
